---
datasets:
  - name: sales
    type: file
    format: json
    landing_path: abfss://landing@staingesttask01.dfs.core.windows.net/sales/incoming/
    bronze_path: abfss://bronze@staingesttask01.dfs.core.windows.net/sales/
    silver_path: abfss://silver@staingesttask01.dfs.core.windows.net/sales/
    gold_path: abfss://gold@staingesttask01.dfs.core.windows.net/sales/
    partition_cols: [ingest_date]
    schema: /Volumes/adbingesttask01/default/confs/sales.json
    autoloader:
      schemaLocation: abfss://bronze@staingesttask01.dfs.core.windows.net/sales/_schema
      checkpointLocation: abfss://bronze@staingesttask01.dfs.core.windows.net/sales/_checkpoint
    batch:
      enabled: true
      trigger: availableNow
    streaming:
      enabled: false

  - name: events
    type: kafka
    format: json
    kafka:
      bootstrapServers: "pkc-qr9n1m.spaincentral.azure.confluent.cloud:9092"
      subscribePattern: "farmia-events-iot"
      "kafka.security.protocol": "SASL_SSL"
      "kafka.sasl.mechanism": "PLAIN"
      api_key: "EVMKISYYZRTQFARA"
    bronze_path: abfss://bronze@staingesttask01.dfs.core.windows.net/events/
    partition_cols: [ingest_date]
    checkpointLocation: abfss://bronze@staingesttask01.dfs.core.windows.net/events/_checkpoint
    streaming:
      enabled: true
...